apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksrivk8s-f741"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aksrivk8s-f741
  template:
    metadata:
      labels:
        app: "aksrivk8s-f741"
    spec:
      containers:
        - name: "aksrivk8s-f741"
          image: "aksrivacr1.azurecr.io/aksrivk8s"
          ports:
          - containerPort: 80
