apiVersion: v1
kind: Service
metadata:
    name: "aksrivk8s-7794"
    labels:
        app: "aksrivk8s-7794"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksrivk8s-7794"