apiVersion: v1
kind: Service
metadata:
    name: aksrivk8s-new
    labels:
        app: aksrivk8s-new
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: aksrivk8s-new
