on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aksrivacr1.azurecr.io
        username: ${{ secrets.acr_aksrivacr1_username }}
        password: ${{ secrets.acr_aksrivacr1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/.devcontainer" -f  ".devcontainer/Dockerfile" -t aksrivacr1.azurecr.io/aksrivk8snew:${{ github.sha }}
        docker push aksrivacr1.azurecr.io/aksrivk8snew:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksrivk8snew_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksrivk8s-new9a27 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksrivk8s-new9a27`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksrivk8s-new9a27
        container-registry-url: aksrivacr1.azurecr.io
        container-registry-username: ${{ secrets.acr_aksrivacr1_username }}
        container-registry-password: ${{ secrets.acr_aksrivacr1_password }}
        secret-name: aksrivk8snewdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aksrivk8s-new9a27
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          aksrivacr1.azurecr.io/aksrivk8snew:${{ github.sha }}
        imagepullsecrets: |
          aksrivk8snewdockerauth